### ISSUE TITLE
[Bug]: Behavioral time series traces not being ploted

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwbwidgets#296]
### What happened?

Example:

![image](https://github.com/NeurodataWithoutBorders/nwbwidgets/assets/24541631/5099a88b-8d4d-4d03-b608-18bffc872d3b)

For this file:
```
nwbfile.processing["behavior"].data_interfaces["BehavioralTimeSeries"].time_series
```

```
{'running_velocity': running_velocity pynwb.base.TimeSeries at 0x140342160473008
 Fields:
   comments: no comments
   conversion: 1.0
   data: <HDF5 dataset "data": shape (246659,), type "<f4">
   description: Velocity of the mouse on a rotating disc.
   interval: 1
   offset: 0.0
   resolution: -1.0
   timestamps: <HDF5 dataset "timestamps": shape (246659,), type "<f8">
   timestamps_unit: seconds
   unit: cm/s}
```

### Operating System

Linux

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/nwbwidgets/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbwidgets/issues)?
